sudo: required

services:
  - docker

env:
  matrix :
    - env:
      VERSION: '8.7.0'
    - env:
      VERSION: '6.11.4'
    - env:
      VERSION: '4.8.4'

install:
  - docker build -t "lgatica/node-zmq:$VERSION" "$VERSION"

script:
  - docker run --rm "lgatica/node-zmq:$VERSION" node --version
