---
sudo: required

services:
  - docker

env:
  matrix:
    - env:
      VERSION: '9.2.0'
    - env:
      VERSION: '8.9.1'
    - env:
      VERSION: '6.12.0'
    - env:
      VERSION: '4.8.6'

install:
  - docker build -t "lgatica/node-zmq:$VERSION" "$VERSION"

script:
  - docker run --rm "lgatica/node-zmq:$VERSION" node --version
